[package]
name = "reiha"
version = "1.2.1"
authors = ["bk <boris.komarov@proton.me>"]
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
dirs = "6.0.0"
macroquad = "0.4.14"
macroquad-canvas = "0.4.1"
regex = "1.11.1"
